[package]
name = "maker-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
core_affinity = "0.8"
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false }
rtrb = "=0.3.4"
serde = { version = "1", features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["rt", "sync", "time"] }
